<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="WeightSensor" Id="{9c9a8d30-bf02-4b6b-a6ef-1b857fd4298b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK WeightSensor IMPLEMENTS ITF_AnalogSensor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	AI_WPWeight AT %I* : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Value" Id="{0bc90006-697b-4de8-867b-f25d5aac15d8}">
      <Declaration><![CDATA[PROPERTY Value : INT]]></Declaration>
      <Get Name="Get" Id="{56d0623e-779f-4ef9-8f01-12ead08c35e2}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Value := AI_WPWeight;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="WeightSensor">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="WeightSensor.Value.Get">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>