<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="Ramp" Id="{17692bb4-989c-44d5-827a-7486b12de95c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Ramp
VAR_INPUT
END_VAR
VAR_OUTPUT
	m_presenceSensorRampFull : PresenceSensor;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Ramp">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>