<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="PropotionalValve" Id="{5b85e889-82b8-4c25-8b3a-ea9ac4cc4e30}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PropotionalValve
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	//Hardware
	AO_SetPressure AT %Q* : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Pressure" Id="{419427f6-2b16-4457-9e6d-8b72af4c3f15}">
      <Declaration><![CDATA[PROPERTY Pressure : INT]]></Declaration>
      <Set Name="Set" Id="{894b5635-5846-4a35-b9cc-1ff7b586da00}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[AO_SetPressure := Pressure;
]]></ST>
        </Implementation>
      </Set>
    </Property>
    <LineIds Name="PropotionalValve">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="PropotionalValve.Pressure.Set">
      <LineId Id="2" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>