<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="RefeedingConveyor" Id="{fa0aebc4-ed9f-4c35-827c-2b417d6323eb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK RefeedingConveyor EXTENDS Conveyor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	//Sensors
	m_PresencesensorStart : PresenceSensor;
	m_PresencesensorEnd : PresenceSensor;
	
	//Pusher
	m_Switch : Switch;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Methods" Id="{967d58bb-f7ca-42a9-af62-d96b6810a3c4}" />
    <Folder Name="Properties" Id="{dfae9a42-80d3-4208-b526-db2e7c78b19e}" />
    <Method Name="METH_Switch_Extend" Id="{f6ff43cd-212b-4b09-bb0d-7a4aad67eb9f}" FolderPath="Methods\">
      <Declaration><![CDATA[METHOD METH_Switch_Extend : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[m_Switch.METH_Extend();]]></ST>
      </Implementation>
    </Method>
    <Method Name="METH_Switch_Retract" Id="{a1cdef5b-49b5-48eb-badd-90d79bc00a40}" FolderPath="Methods\">
      <Declaration><![CDATA[METHOD METH_Switch_Retract : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[m_Switch.METH_Retract();]]></ST>
      </Implementation>
    </Method>
    <Property Name="WPAtEnd" Id="{93b1b83e-a5bf-4f45-a588-281a08b8167f}" FolderPath="Properties\">
      <Declaration><![CDATA[PROPERTY WPAtEnd : BOOL]]></Declaration>
      <Get Name="Get" Id="{ef6fc39e-1c0b-4945-bdc5-0db5ad3573a5}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[WPAtEnd := m_PresencesensorEnd.Value;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WPAtStart" Id="{478d4f0d-56b9-4a3f-ab25-d23c7f82157c}" FolderPath="Properties\">
      <Declaration><![CDATA[PROPERTY WPAtStart : BOOL]]></Declaration>
      <Get Name="Get" Id="{91dd4b66-0380-482e-98c0-de0e6e0fda2c}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[WPAtStart := m_PresencesensorStart.Value;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="RefeedingConveyor">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="RefeedingConveyor.METH_Switch_Extend">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="RefeedingConveyor.METH_Switch_Retract">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="RefeedingConveyor.WPAtEnd.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="RefeedingConveyor.WPAtStart.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>