<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="BaseComponent" Id="{5e455814-cab3-4c57-bf18-d03963995e63}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK BaseComponent
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="BaseComponent">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>