<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="BaseComponent" Id="{80e437a2-fb55-4e30-826c-b89462bc5b3a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK BaseComponent
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="BaseComponent">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>