<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="BaseCarrier" Id="{b216d8a6-3a8b-483a-806a-2347eb7ec6e4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK BaseCarrier EXTENDS BaseComponent
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	Motor : Motor;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="BaseCarrier">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>