<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="PressureSensor" Id="{0cf60463-ace6-4c96-91c5-54c6f310aeb6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PressureSensor IMPLEMENTS ITF_AnalogSensor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	//Hardware
	AI_CurrentPressure AT %I* : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Value" Id="{1ec48ceb-72ca-434b-9146-7f6a915f7385}">
      <Declaration><![CDATA[PROPERTY Value : INT]]></Declaration>
      <Get Name="Get" Id="{2524344c-0044-4014-ad0f-9ea03ea63af5}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Value := AI_CurrentPressure;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="PressureSensor">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="PressureSensor.Value.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>