<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="PresenceSensor" Id="{198d39e5-5ee9-4fa6-a367-84fcc42193f6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PresenceSensor IMPLEMENTS ITF_BinarySensor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	DI_WPDetected AT %I* : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Value" Id="{03f98580-06f3-40ed-ac76-171736b50910}">
      <Declaration><![CDATA[PROPERTY Value : BOOL]]></Declaration>
      <Get Name="Get" Id="{8365c618-6d09-4a92-a9c3-fd6075546b66}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Value := DI_WPDetected;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="PresenceSensor">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="PresenceSensor.Value.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>