<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="BaseCylinder" Id="{0fc64f5a-1ee9-413f-9cbc-5836d5f79a93}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT BaseCylinder IMPLEMENTS ITF_Cylinder
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	//Hardware
	DI_Extended AT %I* : BOOL;
	DI_Retracted AT %I* : BOOL;
	DO_Extend AT %Q* : BOOL;
	//NOT USED BUT USABLE	
	DI_BoundaryPressure AT %I* : BOOL;
	DI_BoundaryFlowPressure AT %I* : BOOL;
	AI_PressureSensor AT %I* : INT;
	AI_FlowPressure AT %I* : INT;
	AI_PositionTransmitter AT %I* : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Extended" Id="{283f46f2-b4ba-4a4c-89b0-c22d3a6bae68}">
      <Declaration><![CDATA[PROPERTY Extended : BOOL]]></Declaration>
      <Get Name="Get" Id="{b6f9aef2-3541-415c-90b5-e54255501b41}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Extended := DI_Extended;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="METH_Extend" Id="{a919f99e-6a78-47eb-839b-1a0df0b366d7}">
      <Declaration><![CDATA[METHOD ABSTRACT METH_Extend : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="METH_Retract" Id="{23e0d501-f25e-416e-b5ed-b063d603a3a7}">
      <Declaration><![CDATA[METHOD ABSTRACT METH_Retract : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="Retracted" Id="{5700e9a8-67a6-40d5-ba2e-6a34df2ffd2a}">
      <Declaration><![CDATA[PROPERTY Retracted : BOOL]]></Declaration>
      <Get Name="Get" Id="{b37b52dd-1411-4925-97db-c533348bcabc}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Retracted := DI_Retracted;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="BaseCylinder">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="BaseCylinder.Extended.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="BaseCylinder.METH_Extend">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="BaseCylinder.METH_Retract">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="BaseCylinder.Retracted.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>