<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="BaseGripper" Id="{fac26416-acca-4852-af75-96dabb5316b0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK BaseGripper
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="BaseGripper">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>