<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="BaseGripper" Id="{328c9d79-6f6a-4f42-95c9-9fd65dfe9285}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK BaseGripper
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="BaseGripper">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>